/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AlbumEntry {
  'id' : Id,
  'date' : bigint,
  'blobIds' : Array<BlobId>,
  'description' : string,
}
export type BlobId = string;
export interface ChatMessage {
  'id' : Id,
  'content' : string,
  'sender' : Principal,
  'timestamp' : bigint,
  'senderName' : string,
}
export type Id = bigint;
export interface MealMenu {
  'date' : bigint,
  'breakfast' : string,
  'lunch' : string,
  'notes' : string,
  'dinner' : string,
}
export interface PendingItem {
  'id' : Id,
  'title' : string,
  'watchType' : WatchType,
  'posterUrl' : [] | [string],
  'notes' : string,
}
export type Time = bigint;
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface WatchItem {
  'id' : Id,
  'status' : WatchStatus,
  'review' : string,
  'title' : string,
  'watchType' : WatchType,
  'pausedAtMin' : [] | [bigint],
  'posterUrl' : [] | [string],
  'notes' : string,
  'rating' : bigint,
  'currentEpisode' : [] | [string],
}
export type WatchStatus = { 'pending' : null } |
  { 'completed' : null } |
  { 'watching' : null };
export type WatchType = { 'movie' : null } |
  { 'series' : null };
export interface _ImmutableObjectStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _ImmutableObjectStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _ImmutableObjectStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_immutableObjectStorageBlobsAreLive' : ActorMethod<
    [Array<Uint8Array>],
    Array<boolean>
  >,
  '_immutableObjectStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_immutableObjectStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_immutableObjectStorageCreateCertificate' : ActorMethod<
    [string],
    _ImmutableObjectStorageCreateCertificateResult
  >,
  '_immutableObjectStorageRefillCashier' : ActorMethod<
    [[] | [_ImmutableObjectStorageRefillInformation]],
    _ImmutableObjectStorageRefillResult
  >,
  '_immutableObjectStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControl' : ActorMethod<[], undefined>,
  'addPhotoToAlbumEntry' : ActorMethod<[bigint, BlobId], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createAlbumEntry' : ActorMethod<[bigint, string], Id>,
  'createChatMessage' : ActorMethod<
    [string],
    { 'ok' : ChatMessage } |
      { 'err' : string }
  >,
  'createPendingItem' : ActorMethod<[PendingItem], Id>,
  'createWatchItem' : ActorMethod<[WatchItem], Id>,
  'deleteAlbumEntry' : ActorMethod<[bigint], undefined>,
  'deleteMealMenu' : ActorMethod<[bigint], undefined>,
  'deletePendingItem' : ActorMethod<[Id], undefined>,
  'deletePhoto' : ActorMethod<[BlobId], undefined>,
  'deleteWatchItem' : ActorMethod<[Id], undefined>,
  'getAlbumEntryByDate' : ActorMethod<[bigint], [] | [AlbumEntry]>,
  'getAllAlbumEntries' : ActorMethod<[], Array<AlbumEntry>>,
  'getAllChatMessages' : ActorMethod<[], Array<ChatMessage>>,
  'getAllMealMenus' : ActorMethod<[], Array<MealMenu>>,
  'getAllPendingItems' : ActorMethod<[], Array<PendingItem>>,
  'getAllWatchItems' : ActorMethod<[], Array<WatchItem>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getLastUpdated' : ActorMethod<[], Time>,
  'getMealMenuByDate' : ActorMethod<[bigint], MealMenu>,
  'getPendingItem' : ActorMethod<[bigint], PendingItem>,
  'getTodaysMenu' : ActorMethod<[], [] | [MealMenu]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getWatchItem' : ActorMethod<[Id], WatchItem>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'removePhotoFromAlbumEntry' : ActorMethod<[bigint, BlobId], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updatePendingItem' : ActorMethod<[Id, PendingItem], undefined>,
  'updateWatchItem' : ActorMethod<[Id, WatchItem], undefined>,
  'uploadPhoto' : ActorMethod<[BlobId], BlobId>,
  'upsertMealMenu' : ActorMethod<[MealMenu], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];