/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type Id = bigint;
export interface MealMenu {
  'date' : bigint,
  'breakfast' : string,
  'lunch' : string,
  'notes' : string,
  'dinner' : string,
}
export interface PendingItem {
  'id' : Id,
  'title' : string,
  'watchType' : WatchType,
  'notes' : string,
}
export type Time = bigint;
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface WatchItem {
  'id' : Id,
  'status' : WatchStatus,
  'title' : string,
  'watchType' : WatchType,
  'pausedAtMin' : [] | [bigint],
  'notes' : string,
}
export type WatchStatus = { 'pending' : null } |
  { 'completed' : null } |
  { 'watching' : null };
export type WatchType = { 'movie' : null } |
  { 'series' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createPendingItem' : ActorMethod<[PendingItem], Id>,
  'createWatchItem' : ActorMethod<[WatchItem], Id>,
  'deleteMealMenu' : ActorMethod<[bigint], undefined>,
  'deletePendingItem' : ActorMethod<[Id], undefined>,
  'deleteWatchItem' : ActorMethod<[Id], undefined>,
  'getAllMealMenus' : ActorMethod<[], Array<MealMenu>>,
  'getAllPendingItems' : ActorMethod<[], Array<PendingItem>>,
  'getAllWatchItems' : ActorMethod<[], Array<WatchItem>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getLastUpdated' : ActorMethod<[], Time>,
  'getMealMenuByDate' : ActorMethod<[bigint], MealMenu>,
  'getPendingItem' : ActorMethod<[bigint], PendingItem>,
  'getTodaysMenu' : ActorMethod<[], [] | [MealMenu]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getWatchItem' : ActorMethod<[Id], WatchItem>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updatePendingItem' : ActorMethod<[Id, PendingItem], undefined>,
  'updateWatchItem' : ActorMethod<[Id, WatchItem], undefined>,
  'upsertMealMenu' : ActorMethod<[MealMenu], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];