/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Id = IDL.Nat;
export const WatchType = IDL.Variant({
  'movie' : IDL.Null,
  'series' : IDL.Null,
});
export const PendingItem = IDL.Record({
  'id' : Id,
  'title' : IDL.Text,
  'watchType' : WatchType,
  'notes' : IDL.Text,
});
export const WatchStatus = IDL.Variant({
  'pending' : IDL.Null,
  'completed' : IDL.Null,
  'watching' : IDL.Null,
});
export const WatchItem = IDL.Record({
  'id' : Id,
  'status' : WatchStatus,
  'title' : IDL.Text,
  'watchType' : WatchType,
  'pausedAtMin' : IDL.Opt(IDL.Nat),
  'notes' : IDL.Text,
});
export const MealMenu = IDL.Record({
  'date' : IDL.Int,
  'breakfast' : IDL.Text,
  'lunch' : IDL.Text,
  'notes' : IDL.Text,
  'dinner' : IDL.Text,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const Time = IDL.Int;

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createPendingItem' : IDL.Func([PendingItem], [Id], []),
  'createWatchItem' : IDL.Func([WatchItem], [Id], []),
  'deleteMealMenu' : IDL.Func([IDL.Int], [], []),
  'deletePendingItem' : IDL.Func([Id], [], []),
  'deleteWatchItem' : IDL.Func([Id], [], []),
  'getAllMealMenus' : IDL.Func([], [IDL.Vec(MealMenu)], ['query']),
  'getAllPendingItems' : IDL.Func([], [IDL.Vec(PendingItem)], ['query']),
  'getAllWatchItems' : IDL.Func([], [IDL.Vec(WatchItem)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getLastUpdated' : IDL.Func([], [Time], ['query']),
  'getMealMenuByDate' : IDL.Func([IDL.Int], [MealMenu], ['query']),
  'getPendingItem' : IDL.Func([IDL.Nat], [PendingItem], ['query']),
  'getTodaysMenu' : IDL.Func([], [IDL.Opt(MealMenu)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getWatchItem' : IDL.Func([Id], [WatchItem], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updatePendingItem' : IDL.Func([Id, PendingItem], [], []),
  'updateWatchItem' : IDL.Func([Id, WatchItem], [], []),
  'upsertMealMenu' : IDL.Func([MealMenu], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Id = IDL.Nat;
  const WatchType = IDL.Variant({ 'movie' : IDL.Null, 'series' : IDL.Null });
  const PendingItem = IDL.Record({
    'id' : Id,
    'title' : IDL.Text,
    'watchType' : WatchType,
    'notes' : IDL.Text,
  });
  const WatchStatus = IDL.Variant({
    'pending' : IDL.Null,
    'completed' : IDL.Null,
    'watching' : IDL.Null,
  });
  const WatchItem = IDL.Record({
    'id' : Id,
    'status' : WatchStatus,
    'title' : IDL.Text,
    'watchType' : WatchType,
    'pausedAtMin' : IDL.Opt(IDL.Nat),
    'notes' : IDL.Text,
  });
  const MealMenu = IDL.Record({
    'date' : IDL.Int,
    'breakfast' : IDL.Text,
    'lunch' : IDL.Text,
    'notes' : IDL.Text,
    'dinner' : IDL.Text,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const Time = IDL.Int;
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createPendingItem' : IDL.Func([PendingItem], [Id], []),
    'createWatchItem' : IDL.Func([WatchItem], [Id], []),
    'deleteMealMenu' : IDL.Func([IDL.Int], [], []),
    'deletePendingItem' : IDL.Func([Id], [], []),
    'deleteWatchItem' : IDL.Func([Id], [], []),
    'getAllMealMenus' : IDL.Func([], [IDL.Vec(MealMenu)], ['query']),
    'getAllPendingItems' : IDL.Func([], [IDL.Vec(PendingItem)], ['query']),
    'getAllWatchItems' : IDL.Func([], [IDL.Vec(WatchItem)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getLastUpdated' : IDL.Func([], [Time], ['query']),
    'getMealMenuByDate' : IDL.Func([IDL.Int], [MealMenu], ['query']),
    'getPendingItem' : IDL.Func([IDL.Nat], [PendingItem], ['query']),
    'getTodaysMenu' : IDL.Func([], [IDL.Opt(MealMenu)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getWatchItem' : IDL.Func([Id], [WatchItem], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updatePendingItem' : IDL.Func([Id, PendingItem], [], []),
    'updateWatchItem' : IDL.Func([Id, WatchItem], [], []),
    'upsertMealMenu' : IDL.Func([MealMenu], [], []),
  });
};

export const init = ({ IDL }) => { return []; };