/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface WatchItem {
    id: Id;
    status: WatchStatus;
    title: string;
    watchType: WatchType;
    pausedAtMin?: bigint;
    notes: string;
}
export type Time = bigint;
export type Id = bigint;
export interface MealMenu {
    date: bigint;
    breakfast: string;
    lunch: string;
    notes: string;
    dinner: string;
}
export interface PendingItem {
    id: Id;
    title: string;
    watchType: WatchType;
    notes: string;
}
export interface UserProfile {
    name: string;
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export enum WatchStatus {
    pending = "pending",
    completed = "completed",
    watching = "watching"
}
export enum WatchType {
    movie = "movie",
    series = "series"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createPendingItem(input: PendingItem): Promise<Id>;
    createWatchItem(input: WatchItem): Promise<Id>;
    deleteMealMenu(date: bigint): Promise<void>;
    deletePendingItem(id: Id): Promise<void>;
    deleteWatchItem(id: Id): Promise<void>;
    getAllMealMenus(): Promise<Array<MealMenu>>;
    getAllPendingItems(): Promise<Array<PendingItem>>;
    getAllWatchItems(): Promise<Array<WatchItem>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getLastUpdated(): Promise<Time>;
    getMealMenuByDate(date: bigint): Promise<MealMenu>;
    getPendingItem(id: bigint): Promise<PendingItem>;
    getTodaysMenu(): Promise<MealMenu | null>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    getWatchItem(id: Id): Promise<WatchItem>;
    isCallerAdmin(): Promise<boolean>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    updatePendingItem(id: Id, item: PendingItem): Promise<void>;
    updateWatchItem(id: Id, item: WatchItem): Promise<void>;
    upsertMealMenu(menu: MealMenu): Promise<void>;
}
import type { Id as _Id, MealMenu as _MealMenu, PendingItem as _PendingItem, UserProfile as _UserProfile, UserRole as _UserRole, WatchItem as _WatchItem, WatchStatus as _WatchStatus, WatchType as _WatchType } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createPendingItem(arg0: PendingItem): Promise<Id> {
        if (this.processError) {
            try {
                const result = await this.actor.createPendingItem(to_candid_PendingItem_n3(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createPendingItem(to_candid_PendingItem_n3(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async createWatchItem(arg0: WatchItem): Promise<Id> {
        if (this.processError) {
            try {
                const result = await this.actor.createWatchItem(to_candid_WatchItem_n7(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createWatchItem(to_candid_WatchItem_n7(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async deleteMealMenu(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteMealMenu(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteMealMenu(arg0);
            return result;
        }
    }
    async deletePendingItem(arg0: Id): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deletePendingItem(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deletePendingItem(arg0);
            return result;
        }
    }
    async deleteWatchItem(arg0: Id): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteWatchItem(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteWatchItem(arg0);
            return result;
        }
    }
    async getAllMealMenus(): Promise<Array<MealMenu>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllMealMenus();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllMealMenus();
            return result;
        }
    }
    async getAllPendingItems(): Promise<Array<PendingItem>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllPendingItems();
                return from_candid_vec_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllPendingItems();
            return from_candid_vec_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllWatchItems(): Promise<Array<WatchItem>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllWatchItems();
                return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllWatchItems();
            return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async getLastUpdated(): Promise<Time> {
        if (this.processError) {
            try {
                const result = await this.actor.getLastUpdated();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLastUpdated();
            return result;
        }
    }
    async getMealMenuByDate(arg0: bigint): Promise<MealMenu> {
        if (this.processError) {
            try {
                const result = await this.actor.getMealMenuByDate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMealMenuByDate(arg0);
            return result;
        }
    }
    async getPendingItem(arg0: bigint): Promise<PendingItem> {
        if (this.processError) {
            try {
                const result = await this.actor.getPendingItem(arg0);
                return from_candid_PendingItem_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPendingItem(arg0);
            return from_candid_PendingItem_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTodaysMenu(): Promise<MealMenu | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getTodaysMenu();
                return from_candid_opt_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTodaysMenu();
            return from_candid_opt_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async getWatchItem(arg0: Id): Promise<WatchItem> {
        if (this.processError) {
            try {
                const result = await this.actor.getWatchItem(arg0);
                return from_candid_WatchItem_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getWatchItem(arg0);
            return from_candid_WatchItem_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async updatePendingItem(arg0: Id, arg1: PendingItem): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updatePendingItem(arg0, to_candid_PendingItem_n3(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updatePendingItem(arg0, to_candid_PendingItem_n3(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateWatchItem(arg0: Id, arg1: WatchItem): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateWatchItem(arg0, to_candid_WatchItem_n7(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateWatchItem(arg0, to_candid_WatchItem_n7(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async upsertMealMenu(arg0: MealMenu): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.upsertMealMenu(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.upsertMealMenu(arg0);
            return result;
        }
    }
}
function from_candid_PendingItem_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PendingItem): PendingItem {
    return from_candid_record_n13(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n24(_uploadFile, _downloadFile, value);
}
function from_candid_WatchItem_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _WatchItem): WatchItem {
    return from_candid_record_n18(_uploadFile, _downloadFile, value);
}
function from_candid_WatchStatus_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _WatchStatus): WatchStatus {
    return from_candid_variant_n20(_uploadFile, _downloadFile, value);
}
function from_candid_WatchType_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _WatchType): WatchType {
    return from_candid_variant_n15(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_MealMenu]): MealMenu | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _Id;
    title: string;
    watchType: _WatchType;
    notes: string;
}): {
    id: Id;
    title: string;
    watchType: WatchType;
    notes: string;
} {
    return {
        id: value.id,
        title: value.title,
        watchType: from_candid_WatchType_n14(_uploadFile, _downloadFile, value.watchType),
        notes: value.notes
    };
}
function from_candid_record_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _Id;
    status: _WatchStatus;
    title: string;
    watchType: _WatchType;
    pausedAtMin: [] | [bigint];
    notes: string;
}): {
    id: Id;
    status: WatchStatus;
    title: string;
    watchType: WatchType;
    pausedAtMin?: bigint;
    notes: string;
} {
    return {
        id: value.id,
        status: from_candid_WatchStatus_n19(_uploadFile, _downloadFile, value.status),
        title: value.title,
        watchType: from_candid_WatchType_n14(_uploadFile, _downloadFile, value.watchType),
        pausedAtMin: record_opt_to_undefined(from_candid_opt_n21(_uploadFile, _downloadFile, value.pausedAtMin)),
        notes: value.notes
    };
}
function from_candid_variant_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    movie: null;
} | {
    series: null;
}): WatchType {
    return "movie" in value ? WatchType.movie : "series" in value ? WatchType.series : value;
}
function from_candid_variant_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    completed: null;
} | {
    watching: null;
}): WatchStatus {
    return "pending" in value ? WatchStatus.pending : "completed" in value ? WatchStatus.completed : "watching" in value ? WatchStatus.watching : value;
}
function from_candid_variant_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_PendingItem>): Array<PendingItem> {
    return value.map((x)=>from_candid_PendingItem_n12(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_WatchItem>): Array<WatchItem> {
    return value.map((x)=>from_candid_WatchItem_n17(_uploadFile, _downloadFile, x));
}
function to_candid_PendingItem_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PendingItem): _PendingItem {
    return to_candid_record_n4(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_WatchItem_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: WatchItem): _WatchItem {
    return to_candid_record_n8(_uploadFile, _downloadFile, value);
}
function to_candid_WatchStatus_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: WatchStatus): _WatchStatus {
    return to_candid_variant_n10(_uploadFile, _downloadFile, value);
}
function to_candid_WatchType_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: WatchType): _WatchType {
    return to_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function to_candid_record_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: Id;
    title: string;
    watchType: WatchType;
    notes: string;
}): {
    id: _Id;
    title: string;
    watchType: _WatchType;
    notes: string;
} {
    return {
        id: value.id,
        title: value.title,
        watchType: to_candid_WatchType_n5(_uploadFile, _downloadFile, value.watchType),
        notes: value.notes
    };
}
function to_candid_record_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: Id;
    status: WatchStatus;
    title: string;
    watchType: WatchType;
    pausedAtMin?: bigint;
    notes: string;
}): {
    id: _Id;
    status: _WatchStatus;
    title: string;
    watchType: _WatchType;
    pausedAtMin: [] | [bigint];
    notes: string;
} {
    return {
        id: value.id,
        status: to_candid_WatchStatus_n9(_uploadFile, _downloadFile, value.status),
        title: value.title,
        watchType: to_candid_WatchType_n5(_uploadFile, _downloadFile, value.watchType),
        pausedAtMin: value.pausedAtMin ? candid_some(value.pausedAtMin) : candid_none(),
        notes: value.notes
    };
}
function to_candid_variant_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: WatchStatus): {
    pending: null;
} | {
    completed: null;
} | {
    watching: null;
} {
    return value == WatchStatus.pending ? {
        pending: null
    } : value == WatchStatus.completed ? {
        completed: null
    } : value == WatchStatus.watching ? {
        watching: null
    } : value;
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: WatchType): {
    movie: null;
} | {
    series: null;
} {
    return value == WatchType.movie ? {
        movie: null
    } : value == WatchType.series ? {
        series: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
